#!/bin/sh
set -e -u
cp -r conftest.py tests "$AUTOPKGTEST_TMP"
cd "$AUTOPKGTEST_TMP/"
export PYTHONWARNINGS=d
(pyversions -i; py3versions -i) \
| tr ' ' '\n' \
| xargs -I {} env {} \
  -m pytest tests 2>&1
